root: true
env:
    node: true
parser: '@typescript-eslint/parser'
parserOptions:
    project:
        - './tsconfig.json'
plugins:
    - '@typescript-eslint'
extends:
    - 'eslint:recommended'
    - 'plugin:@typescript-eslint/recommended'
    - 'plugin:@typescript-eslint/recommended-requiring-type-checking'
ignorePatterns:
    - dist
    - dist-dev
    - dist-cjs
    # I would like to lint scripts, but it doesn't support top level await. "not stage 4" yet supported in node/chrome, yeah sure mate.
    - scripts 
rules:
    '@typescript-eslint/restrict-template-expressions': off
    'no-constant-condition':
        - off
        - checkLoops: false
    '@typescript-eslint/no-non-null-assertion': off
    '@typescript-eslint/explicit-module-boundary-types': off
    'prefer-const': warn
    'eqeqeq':
        - error
        - always
    quotes:
        - error
        - single
        - avoidEscape: true
    eol-last:
        - error
        - always
    '@typescript-eslint/no-floating-promises': off
    no-unused-vars: off
    '@typescript-eslint/no-unused-vars':
        - warn
        - argsIgnorePattern: ^_|t$
          varsIgnorePattern: ^_|t$
    'no-empty-function': off
    '@typescript-eslint/no-namespace': off
    '@typescript-eslint/no-empty-function': off
    '@typescript-eslint/no-explicit-any': off
    no-empty:
        - error
        - allowEmptyCatch: true
overrides:
    - files: 
        - "*.js"
        - "*.cjs"
      parser: espree
      parserOptions:
            ecmaVersion: 2021
